version: '3'
services:
  nginx:
    image: chipsofttech/nginx:latest
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ./application:/var/www/html
    networks:
     - appnet
    restart: always
  php:
    image: chipsofttech/php:latest
    volumes:
     - ./application:/var/www/html
    networks:
     - appnet
    restart: always
  redis:
    image: redis:alpine
    networks:
     - appnet
    restart: always
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
     - data:/var/lib/mysql
    networks:
     - appnet
    restart: always 
  ghost:
    image: ghost:1-alpine
    restart: always
    ports:
      - 8080:2368
  jenkins:
    image: "jenkinsci/jenkins"
    restart: always
    ports:
    - "8080:8080"
    volumes:
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
